stages:
  - build
  - test
  - containerize
#  - deploy


build:
  stage: build
  image: node:15.11.0-alpine3.10
  script:
    - npm install
    - npm run build
  cache:
    paths:
      - dist/
      - node_modules/
#  only:
#    - merge_request
#    - master
test:
  stage: test
  image: node:15.11.0-alpine3.10
  script:
    - npm test
#  only:
#    - merge_requests
#    - master
  cache:
    paths:
      - dist/
      - node_modules/

containerize-todoservice:
  stage: containerize
  image: docker:dind
  script:
    - docker build -t esdp/todoservice .
    - docker login -u $ESDP_USER -p $ESDP_PASSWORD
    - docker push esdp/todoservice
    - docker rm esdp/todoservice
  only:
    - master