.cache: &cache
  cache:
    paths:
      - /todoservice/dist/
      - /todoservice/node_modules/


stages:
  - build
  - test
  #  - containerize
  - deploy


build:
  <<: *cache
  stage: build
  image: node:15.11.0-alpine3.10
  script:
    - cd todoservice
    - npm install
    - npm run build
#  only:
#    - merge_request
#    - master
test:
  <<: *cache
  stage: test
  image: node:15.11.0-alpine3.10
  script:
    - cd todoservice
    - npm test
#  only:
#    - merge_requests
#    - master

deploy:
  stage: deploy
  <<: *cache
  image: tmaier/docker-compose
  script:
    - docker-compose up -d
    - echo "Started!"
  only:
    - master

#containerize-todoservice:
#  <<: *cache
#  stage: containerize
#  image: docker:latest
#  script:
#    - docker build -t esdpjs1/todoservice .
#    - docker login -u $ESDP_USER -p $ESDP_PASSWORD
#    - docker push esdpjs1/todoservice
#  only:
#    - master