.cache: &cache
  cache:
    paths:
      - dist/
      - node_modules/


stages:
  - build
  - test
  - containerize
#  - deploy


build:
  <<: *cache
  stage: build
  image: node:15.11.0-alpine3.10
  script:
    - npm install
    - npm run build
#  only:
#    - merge_request
#    - master
test:
  <<: *cache
  stage: test
  image: node:15.11.0-alpine3.10
  script:
    - npm test
#  only:
#    - merge_requests
#    - master

containerize-todoservice:
  <<: *cache
  stage: containerize
  image: docker:latest
  script:
    - docker build -t esdpjs1/todoservice .
    - docker login -u $ESDP_USER -p $ESDP_PASSWORD
    - docker push esdpjs1/todoservice
  only:
    - master